theme: jekyll-theme-modernist
title: Linux-WSL2 Archives
description:
show_downloads: true

github:
  repository_url:
  zip_url: https://github.com/linux-wsl2/linux-stable/archive/v5.8.8.zip
  tar_url: https://github.com/linux-wsl2/linux-stable/releases/download/v5.8.8/x64_linux-wsl2_5.8.8.tar.xz
