theme: jekyll-theme-modernist
title: Linux-WSL2 Archives
description: Home to Linux-WSL2
show_downloads: true

github:
  repository_url: https://github.com/linux-wsl2/linux-stable/tree/linux-5.8.y
  tar_url: https://github.com/linux-wsl2/linux-stable/releases/download/v5.8.8/x64_linux-wsl2_5.8.8.tar.xz
